data:extend({
  {
    type = "sprite",
    name = "ltnt_sprite_refresh",
    filename = "__core__/graphics/icons/mip/refresh.png",
    priority = "high",
    width = 32,
    height = 32,
    scale = 1,
  },
  {
    type = "sprite",
    name = "ltnt_sprite_delete",
    filename = "__core__/graphics/icons/mip/trash.png",
    priority = "high",
    width = 32,
    height = 32,
    scale = 1,
  },
  {
    type = "sprite",
    name = "ltnt_sprite_enter",
    filename = "__core__/graphics/icons/mip/expand-dark.png",
    priority = "high",
    width = 32,
    height = 32,
    scale = 1,
  },
  {
    type = "sprite",
    name = "ltnt_sprite_search",
    filename = "__core__/graphics/icons/mip/search.png",
    priority = "high",
    width = 32,
    height = 32,
  },
  {
    type = "sprite",
    name = "ltnt_bt_alert_sprite",
    filename = "__LTN_Tracker__/graphics/bt_with_alert.png",
    priority = "high",
    width = 128,
    height = 128,
    scale = 0.5,
  },
  {
    type = "sprite",
    name = "ltnt_bt_sprite",
    filename = "__base__/graphics/technology/railway.png",
    priority = "high",
    width = 128,
    height = 128,
    scale = 0.5,
  },
  {
    type = "sprite",
    name = "ltnt_warning_sign_sprite",
    filename = "__core__/graphics/icons/alerts/warning-icon.png",
    priority = "high",
    width = 64,
    height = 64,
    scale = 0.5,
  },
})